// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDscrmz1MqwXrLCNbD4yO4_61P-b16w4bk',
    appId: '1:353265714008:web:f8473d1e94b678adef1b2d',
    messagingSenderId: '353265714008',
    projectId: 'fuse-app-f9791',
    authDomain: 'fuse-app-f9791.firebaseapp.com',
    storageBucket: 'fuse-app-f9791.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMIgI09G28MY9itFTZz81ltPoJCzFySug',
    appId: '1:353265714008:android:817d805da029d846ef1b2d',
    messagingSenderId: '353265714008',
    projectId: 'fuse-app-f9791',
    storageBucket: 'fuse-app-f9791.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIeaPtQcCHVNMu8fTtm7ApmmBh49WmKeg',
    appId: '1:353265714008:ios:7d220b7384b71cd6ef1b2d',
    messagingSenderId: '353265714008',
    projectId: 'fuse-app-f9791',
    storageBucket: 'fuse-app-f9791.appspot.com',
    iosClientId: '353265714008-3fal1shurdoh233580qcsa8pqvvbokni.apps.googleusercontent.com',
    iosBundleId: 'com.codegemz.uiControls',
  );
}
